### ISSUE TITLE
In `reduction`, `software` should have `name`, and `version` as attributes but they are the same level

### ISSUE THREAD

**Issue by jfkcooper** [reflectivity/orsopy#109]
```
# reduction:
#   software: Mantid
#   name: Mantid Workbench
#   version: 6.5.0
```
I think should be:

```
# reduction:
#   software: Mantid
#       name: Mantid Workbench
#       version: 6.5.0
```

**Comment by andyfaff** [comment]
@jfkcooper it's not clear where either of those snippets come from. If I do

```python
from orsopy.fileio import Software, Reduction, Person, Orso
p = Person("Andrew", "thingymabob uni")
s = Software('refnx', '1.2')
r = Reduction(s, creator=p)
ef = Orso.empty()
ef.reduction = r
print(ef.to_yaml())
```

I get:

```
data_source:
  owner:
    name: null
    affiliation: null
  experiment:
    title: null
    instrument: null
    start_date: null
    probe: null
  sample:
    name: null
  measurement:
    instrument_settings:
      incident_angle: {magnitude: null}
      wavelength: {magnitude: null}
    data_files: []
reduction:
  software: {name: refnx, version: '1.2'}
  creator:
    name: Andrew
    affiliation: thingymabob uni
columns:
- {name: Qz, unit: 1/angstrom}
- {name: R}
``` 

which looks about right to me. In fact I'm not sure why you get `software: Mantid` instead of just `software:`

**Comment by jfkcooper** [comment]
This may be an artifact of having more than one way of doing the same thing:
"""
from orsopy import fileio
import numpy as np

header = fileio.orso.Orso.empty()

rb_number = 1815260
header.data_source.experiment.probe = 'neutron'
header.data_source.experiment.facility = 'ISIS'  # This may be able to be extracted from Mantid/workspace?
header.data_source.experiment.proposalID = str(rb_number)  # ISIS Specific
header.data_source.experiment.doi = f'10.5286/ISIS.E.RB{rb_number}'  # ISIS Specific

header.reduction.software = 'Mantid'
header.reduction.name = 'Mantid Workbench'
header.reduction.version = str(1.4)

dataset = fileio.orso.OrsoDataset(info=header, data=np.array([np.zeros(4), np.zeros(4)]).T)

save_path = '/Users/joshanielcooper/Dropbox/ISIS/RSE/Reflectometry/test_orso.ort'
if __name__ == '__main__':
    fileio.orso.save_orso(datasets=[dataset], fname=save_path)
"""

**Comment by jfkcooper** [comment]
![image](https://github.com/reflectivity/orsopy/assets/28106479/b6417653-b3fc-40f0-9f5a-e6ab76216e98)

**Comment by andyfaff** [comment]
I think what you're experiencing is the python joy of being able to set attributes on any objects, in any way you see fit. I think the file is being constructed incorrectly.

```
from orsopy import fileio
import numpy as np

header = fileio.orso.Orso.empty()

# the Reduction object does not have an attribute called name
assert not hasattr(header.reduction, 'name')

# the `header.reduction.software` attribute should be a fileio.reduction.Software instance.
# it should not be a string.
assert hasattr(header.reduction, 'software')
assert isinstance(header.reduction.software, fileio.reduction.Software)

# instead you should be setting the name on the software attribute
hasattr(header.reduction.software, 'name')
header.reduction.software.name = "Mantid Workbench"
header.reduction.software.version = '1.4'

print(header.to_yaml())
```

gives:

```
data_source:
  owner:
    name: null
    affiliation: null
  experiment:
    title: null
    instrument: null
    start_date: null
    probe: null
  sample:
    name: null
  measurement:
    instrument_settings:
      incident_angle: {magnitude: null}
      wavelength: {magnitude: null}
      polarization: unpolarized
    data_files: []
reduction:
  software: {name: Mantid Workbench, version: '1.4'}
columns:
- {name: Qz, unit: 1/angstrom}
- {name: R}
```


The files that are being written in the OP aren't valid Orso, in that they don't validate. You can check this with your example:

```
from orsopy import fileio
import numpy as np

header = fileio.orso.Orso.empty()

header.data_source.experiment.probe = 'neutron'

header.reduction.software = 'Mantid'
header.reduction.name = 'Mantid Workbench'
header.reduction.version = str(1.4)

dataset = fileio.orso.OrsoDataset(info=header, data=np.array([np.zeros(4), np.zeros(4)]).T)

fileio.orso.save_orso(datasets=[dataset], fname='test.ort')
fileio.base._read_header_data('test.ort', validate=True)
```

The validation line will fail.
